<?php

/**
 * This file is part of the Spryker Commerce OS.
 * For full license information, please view the LICENSE file that was distributed with this source code.
 */

namespace PyzTest\Zed\Antelope\Business;

use Codeception\Test\Unit;
use PyzTest\Zed\Antelope\AntelopeBusinessTester;

/**
 * Auto-generated group annotations
 *
 * @group PyzTest
 * @group Zed
 * @group Antelope
 * @group Business
 * @group Facade
 * @group AntelopeFacadeTest
 * Add your own group annotations below this line
 */
class AntelopeFacadeTest extends Unit
{
    /**
     * @var \PyzTest\Zed\Antelope\AntelopeBusinessTester
     */
    protected AntelopeBusinessTester $tester;

    /**
     * @return void
     */
    public function testGetAntelopeCollection(): void
    {
        // This is an autogenerated test, please complete me.
        $this->assertTrue(false);
    }
}
