<?php

/**
 * This file is part of the Spryker Commerce OS.
 * For full license information, please view the LICENSE file that was distributed with this source code.
 */

namespace Pyz\Zed\AntelopeDataImport;

use Pyz\Zed\Antelope\Business\AntelopeFacadeInterface;
use Pyz\Zed\DataImport\DataImportDependencyProvider;
use Spryker\Zed\Kernel\Container;

class AntelopeDataImportDependencyProvider extends DataImportDependencyProvider
{
    public const string FACADE_ANTELOPE = 'FACADE_ANTELOPE';

    public function provideBusinessLayerDependencies(Container $container): Container
    {
        $container = parent::provideBusinessLayerDependencies($container); // TODO: Change the autogenerated stub
        $this->addAntelopeFacade($container);

        return $container;
    }

    /**
     * @return void
     */
    private function addAntelopeFacade(Container $container): void
    {
        $container->set(
            static::FACADE_ANTELOPE,
            static fn (): AntelopeFacadeInterface => $container->getLocator()->antelope()->facade(),
        );
    }
}
